name: test

on:
  push:
  pull_request:

jobs:
  package:
    strategy:
      matrix:
        os: [macos-14, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
      - run: uv sync
      - run: uv run python -m py_compile src/habla/habla.py
      - run: uv run python -c "import sherpa_onnx"
      - run: uv build
